name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    name: build and test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.11
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Check formatting
        run: pnpm run format:check
      - name: Build library
        run: pnpm run build
      - name: Unit test
        run: pnpm run test
      - name: Setup playwright
        run: pnpm playwright install --with-deps
      - name: Playwright test
        run: pnpm run test:pw
